### ISSUE TITLE
Tye should use case insensitive string matching between the application name in tye.yaml and launch.json

### ISSUE THREAD

**Issue by ooeygui** [microsoft/vscode-tye#167]
If case is the only difference between launch.json and tye.yaml, the tye extension may not find the launched application.

For example:
tye.yaml
```yaml
name: foo
```

launch.json
```yaml
{
    "applicationName": "FOO",
    "name": "Debug with Tye",
    "preLaunchTask": "tye-run",
    "request": "launch",
    "type": "tye",
    "watch": true
}
```
The tye extension will timeout waiting for FOO, when the application foo started.
